#!/usr/bin/env python

import os, sys
from munin.mongodb import MuninMongoDBPlugin

class MonqueJobsPendingPlugin(MuninMongoDBPlugin):
    args = "-l 0 --base 1000"
    vlabel = "jobs"
    title = "Monque"
    info = "Operations"

    @property
    def fields(self):
        # dynamically create the list 
        self.queues = []
        cur = self.db['monque:queue_stats'].find()
        for row in cur:
            try:
                queue = row['_id']
                self.queues.append(queue)
            except KeyError:
                pass
        return [
            (queue, dict(
                label = "%s_jobs_pending" % queue,
                info = "%s jobs pending" % queue,
                type = "GAUGE",
                min = "0",
                warning = "200",
                critical = "1000"
            )) for queue in self.queues
        ]

    @property
    def title(self):
        return "monque jobs pending"

    def execute(self):
        result = dict()
        cur = self.db['monque:queue_stats'].find()
        for row in cur:
            try:
                queue = row['queue']
                queue_size = int(row.get('size', 0))
            except KeyError:
                pass
            else:
                result['%s_jobs_pending' % queue] = queue_size
        return result

if __name__ == "__main__":
    MonqueJobsPendingPlugin().run()
